code/backend/protected/controllers/MenuController.php
<?php
/**
 * Backend Menu Controller.
 * 
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class MenuController extends BeController{
    
       
        public function __construct($id,$module=null)
	{
		 parent::__construct($id,$module);
                 $this->menu=array(
                        array('label'=>t('cms','Manage Menu'), 'url'=>array('admin'),'linkOptions'=>array('class'=>'button')),
                        array('label'=>t('cms','Add Menu'), 'url'=>array('create'),'linkOptions'=>array('class'=>'button')),
                );
		 
	}
                 
        /**
	 * The function that do Create new Menu
	 * 
	 */
	public function actionCreate()
	{                
		$this->render('menu_create');
	}
        
       
        
        /**
	 * The function that do Manage Menu
	 * 
	 */
	public function actionAdmin()
	{                
		$this->render('menu_admin');
	}
        
        /**
	 * The function that view Menu details
	 * 
	 */
	public function actionView()
	{         
              $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
              $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Menu'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Menu'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('menu_view');
	}
        
        /**
	 * The function that update Menu
	 * 
	 */
	public function actionUpdate()
	{                
                $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;                
                $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Menu'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Menu'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('menu_update',array('id'=>$id));
	}
        
        
        /**
	 * The function is to Delete Menu
	 * 
	 */
	public function actionDelete($id)
	{                            
             GxcHelpers::deleteModel('Menu', $id);          
	}
                    
}

code/backend/protected/controllers/PageController.php
<?php
/**
 * Backend Page Controller.
 * 
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class PageController extends BeController{
    
       
        public function __construct($id,$module=null)
	{
		 parent::__construct($id,$module);
                 $this->menu=array(
                        array('label'=>t('cms','Manage Page'), 'url'=>array('admin'),'linkOptions'=>array('class'=>'button')),
                        array('label'=>t('cms','Add Page'), 'url'=>array('create'),'linkOptions'=>array('class'=>'button')),
                );
		 
	}
                 
        /**
	 * The function that do Create new Page
	 * 
	 */
	public function actionCreate()
	{                
		$this->render('page_create');
	}
        
       
        
        /**
	 * The function that do Manage Page
	 * 
	 */
	public function actionAdmin()
	{                
		$this->render('page_admin');
	}
        
        /**
	 * The function that view Page details
	 * 
	 */
	public function actionView()
	{         
              $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
              $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Page'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Page'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('page_view');
	}
        
        /**
	 * The function that update Page
	 * 
	 */
	public function actionUpdate()
	{                
                $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;                
                $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Page'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Page'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('page_update',array('id'=>$id));
	}
        
        
        /**
	 * The function is to Delete Page
	 * 
	 */
	public function actionDelete($id)
	{                            
             GxcHelpers::deleteModel('Page', $id);          
	}
        
        
        
    public function actionChangeLayout(){
          Page::changeLayout();
    }
        
    public function actionInheritParent(){
          Page::inheritParent();
    }
    
    public function actionChangeParent(){
          Page::changeParent();
    }
             
        /**
	 * This function sugget the Pages
	 * 
	 */
	public function actionSuggestPage()
	{                
            Page::suggestPage();
	}
        
        
        
}

code/backend/protected/controllers/TermController.php
<?php
/**
 * Backend Term Controller.
 * 
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class TermController extends BeController{
    
       
        public function __construct($id,$module=null)
	{
		 parent::__construct($id,$module);
                 $this->menu=array(
                        array('label'=>t('cms','Manage Terms'), 'url'=>array('admin'),'linkOptions'=>array('class'=>'button')),
                        array('label'=>t('cms','Add Term'), 'url'=>array('create'),'linkOptions'=>array('class'=>'button')),
                );
		 
	}
                 
        /**
	 * The function that do Create new Term
	 * 
	 */
	public function actionCreate()
	{                
                
		$this->render('term_create');
	}
        
        
       
        
        /**
	 * The function that do Manage Term
	 * 
	 */
	public function actionAdmin()
	{                
		$this->render('term_admin');
	}
        
        /**
	 * The function that view Term details
	 * 
	 */
	public function actionView()
	{         
              $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
              $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Term'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Term'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('term_view');
	}
        
        /**
	 * The function that update Term
	 * 
	 */
	public function actionUpdate()
	{                
                $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;                
                $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Term'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Term'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('term_update',array());
	}
        
        
        /**
	 * The function is to Delete Term
	 * 
	 */
	public function actionDelete($id)
	{                              
             Term::ajaxDeleteModel($id);
	}
        
         /**
	 * The function is to Delete Term
	 * 
	 */
	public function actionChangeOrder()
	{                                     
             Term::ajaxChangeOrder();
	}
        
        /**
         * 
         * This function is generate Terms based on Taxonomy Id
         */
        public function actionDynamicParentTerms(){
            $taxonomy_id= (int) ($_POST['Term']['taxonomy_id']);
            Term::getTermFromTaxonomy($taxonomy_id);
        }
                    
}

code/backend/protected/controllers/UserController.php
<?php
/**
 * Backend User Controller.
 * 
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class UserController extends BeController{
    
       
    public function __construct($id,$module=null)
	{
	 parent::__construct($id,$module);
                $this->menu=array(
                      
					   array('label'=>t('cms','Manage User'), 'url'=>array('admin'),'linkOptions'=>array('class'=>'button')),
                       array('label'=>t('cms','Create User'), 'url'=>array('create'),'linkOptions'=>array('class'=>'button')),
               );
	 
	}
         /**
	 * The function that do Change Password
	 * 
	 */
	public function actionChangePass()
	{                
                $this->menu=array();                        
                $this->render('user_change_pass');
	}
        
        /**
	 * The function that do Update Settings 
	 * 
	 */
	public function actionUpdateSettings()
	{        
                $this->menu=array();                        
		$this->render('user_update_settings');
	}
        
        /**
	 * The function that do Create new User
	 * 
	 */
	public function actionCreate()
	{                
		$this->render('user_create');
	}
        
        /**
	 * The function that do Manage User
	 * 
	 */
	public function actionAdmin()
	{                
		$this->render('user_admin');
	}
        
        /**
	 * The function that do View User
	 * 
	 */
	public function actionView()
	{         
              $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
              $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this user'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this user'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('user_view');
	}
        
        /**
	 * The function that do Update User
	 * 
	 */
	public function actionUpdate()
	{                
                $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
                
                $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this user'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this user'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('user_update');
	}
        
        /**
	 * The function is to Delete a User
	 * 
	 */
	public function actionDelete($id)
	{                            
            GxcHelpers::deleteModel('User', $id);
	}
                    
}

code/backend/protected/views/layouts/blank.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>	    
	<?php 	        		
		$this->renderPartial('application.views.layouts.header',array());         
    ?>
</head>
<body>
<div class="container" id="page" style="text-align:center">	
    <?php echo $content; ?>	
</div><!-- page -->
</body>
</html>

code/backend/protected/views/layouts/clean.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>		    
	<?php 	        		
		$this->renderPartial('application.views.layouts.header',array());         
    ?>
</head>

<body style="padding:10px">
<div class="container" id="page">  
    <?php echo $content; ?>			
</div><!-- page -->
</body>
</html>

code/backend/protected/views/layouts/error.php
<?php echo $content; ?>

code/backend/protected/views/layouts/header.php
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="language" content="en" />
<?php

        $cs=Yii::app()->clientScript;
        $cssCoreUrl = $cs->getCoreScriptUrl();
        $cs->registerCoreScript('jquery');
        $cs->registerCoreScript('jquery.ui');
        $cs->registerCssFile($cssCoreUrl . '/jui/css/base/jquery-ui.css');
                

        //Publish Files from backend assets folders

        $urlScript =  bu().'/js/backend.js';
	$prettyPhotoScript = bu().'/js/jquery.prettyPhoto.js';
        $cs->registerScriptFile($urlScript, CClientScript::POS_HEAD);
	$cs->registerScriptFile($prettyPhotoScript, CClientScript::POS_HEAD);  
        $cs->registerScriptFile(bu().'/js/jquery.ui.position.js', CClientScript::POS_HEAD);   
        $cs->registerScriptFile(bu().'/js/jquery.contextMenu.js', CClientScript::POS_HEAD);   

?>
<!-- blueprint CSS framework -->
<link rel="stylesheet" type="text/css" href="<?php echo bu(); ?>/css/screen.css" media="screen, projection" />
<link rel="stylesheet" type="text/css" href="<?php echo bu(); ?>/css/print.css" media="print" />
<!--[if lt IE 8]>
<link rel="stylesheet" type="text/css" href="<?php echo bu(); ?>/css/ie.css" media="screen, projection" />
<![endif]-->

<link rel="stylesheet" type="text/css" href="<?php echo bu(); ?>/css/main.css" />
<link rel="stylesheet" type="text/css" href="<?php echo bu(); ?>/css/form.css" />
<link rel="stylesheet" type="text/css" href="<?php echo bu(); ?>/css/prettyPhoto.css" />
<link rel="stylesheet" type="text/css" href="<?php echo bu(); ?>/css/jquery.contextMenu.css" />

<title><?php echo CHtml::encode($this->pageTitle); ?></title>

<script type="text/javascript" charset="utf-8">
	  $(document).ready(function(){
	       $("a[rel^='prettyPhoto']").prettyPhoto({show_title: true,social_tools: '',deeplinking: false});
	  });
</script>

code/backend/protected/views/layouts/login.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>	    
	<?php 	        	
		$this->renderPartial('application.views.layouts.header',array());         
    ?>
</head>
<body>
<div class="container" id="page">
	<div id="header-login" style="margin:0 auto; text-align: center" >		
		<div style="padding-top:60px">
		<img src="<?php echo bu(); ?>/images/logo.png" />
		</div>
	</div>
	<div id="site-content" style="margin:0 auto; width:400px; border-top:0px">
            	<?php echo $content; ?>		
	</div>

</div><!-- page -->
 
</body>
</html>

code/backend/protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>    
	<?php 	        		
		$this->renderPartial('application.views.layouts.header',array());       
    ?>
</head>
<body>

<div class="container" id="page">
	<div id="nav">
		<div class="wrap">
				<ul class="right">				
					<li><?php echo t('cms','Welcome'); ?>, <strong><?php echo user()->getModel('display_name'); ?></strong>&nbsp;|&nbsp;</li>
					<li><a href="<?php echo Yii::app()->request->baseUrl?>/user/updatesettings"><?php echo t('cms','Settings'); ?></a>&nbsp;|&nbsp;</li>
					<li><a href="<?php echo Yii::app()->request->baseUrl?>/user/changepass"><?php echo t('cms','Change Password'); ?></a>&nbsp;|&nbsp;</li>
					<li><a href="<?php echo Yii::app()->request->baseUrl?>/site/logout"><?php echo t('cms','Sign out'); ?></a></li>
				</ul>
				
		</div>			
	</div>
	<div id="header">
		<div style="float:left; padding-left:45px">
		<a href="<?php echo bu(); ?>"><img src="<?php echo bu(); ?>/images/logo2.png"; /></a>
		</div>
		<form id="search-box" method="get" action="#" target="_blank" style="float:left;">
			<input class="topSearchBox" id="topSearchBox" autocomplete="off" type="text" maxlength="2048" name="q" label="Search" placeholder="" aria-haspopup="true" />
			<input type="submit" value="Go" id="searchbutton" class="bebutton" />
		</form>
		<div class="clear"></div>
	</div>

	<div id="site-content">
		<div id="left-sidebar">
            <?php $this->renderPartial('application.views.layouts.menu'); ?>
		</div>
		<div id="main-content-zone">
                        <?php if(isset($this->menu)) :?>
                        <?php if(count($this->menu) >0 ): ?>
			<div class="header-info">
				<?php                                       
                      $this->widget('zii.widgets.CMenu', array(
                              'items'=>$this->menu,
                              'htmlOptions'=>array(),
                      ));                                       
                ?>
			</div>
                        <?php endif; ?>
                        <?php endif; ?>
			<div class="page-content">                                
					<div id="inner" style="width:100%;float:left;">
                        <h2><?php echo (isset($this->titleImage)&&($this->titleImage!=''))? '<img src="'. bu().'/'.$this->titleImage.'" />' : ''; ?><?php echo isset($this->pageTitle)? $this->pageTitle : '';  ?></h2>
                        <?php if (isset($this->pageHint)&&($this->pageHint!='')) : ?>
                            <p><?php echo $this->pageHint; ?></p>
                  		<?php endif; ?>
						<?php echo $content; ?>
					</div>
			</div>
		</div>
		
	</div>

</div><!-- page -->
    <script type="text/javascript">

	$(document).ready(function () {
            //Hide the second level menu
            $('#left-sidebar ul li ul').hide();            
            //Show the second level menu if an item inside it active
            $('li.list_active').parent("ul").show();
            
            $('#left-sidebar').children('ul').children('li').children('a').click(function () {                    
                
                 if($(this).parent().children('ul').length>0){                  
                    $(this).parent().children('ul').toggle();    
                 }
                 
            });
          
            
        });
    </script>
</body>

</html>

code/backend/protected/views/layouts/menu.php
      
<?php
$this->widget('zii.widgets.CMenu',array(
	'encodeLabel'=>false,
	'activateItems'=>true,
	'activeCssClass'=>'list_active',
	'items'=>array(

		//Dasboard Menu 
		array(
			'label'=>'<span id="menu_dashboard" class="micon"></span>'.t('cms','Dashboard'), 
			'url'=>array('/site/index') ,'linkOptions'=>array('class'=>'menu_0'),
			'active'=> ((Yii::app()->controller->id=='site') && (in_array(Yii::app()->controller->action->id,array('index'))) ? true : false)
			),                               

		//Content Menu 
		array(
			'label'=>'<span id="menu_content" class="micon"></span>'.t('cms','Content'),  
			'url'=>'javascript:void(0);','linkOptions'=>array('class'=>'menu_1' ), 
			'itemOptions'=>array('id'=>'menu_1'), 
			'items'=>array(
				array(
					'label'=>t('cms','Create Content'), 
					'url'=>array('/object/create'),
					'active'=>Yii::app()->controller->id=='object' && Yii::app()->controller->action->id=='create'
					),
				array(
					'label'=>t('cms','Draft Content'), 
					'url'=>array('/object/draft'),
					'active'=>Yii::app()->controller->id=='object' && Yii::app()->controller->action->id=='draft'
					),
				array(
					'label'=>t('cms','Pending Content'), 
					'url'=>array('/object/pending'),
					'active'=>Yii::app()->controller->id=='object' && Yii::app()->controller->action->id=='pending'
					),
				array(
					'label'=>t('cms','Published Content'), 
					'url'=>array('/object/published'),
					'active'=>Yii::app()->controller->id=='object' && Yii::app()->controller->action->id=='published'
					),
				array(
					'label'=>t('cms','Manage Content'), 
					'url'=>array('/object/admin'),
					'visible'=>user()->isAdmin ? true : false,
					'active'=> ((Yii::app()->controller->id=='object') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index'))) ? true : false)
					)
				)
			),

		//Category Menu 
		array(
			'label'=>'<span id="menu_taxonomy" class="micon"></span>'.t('cms','Category'), 
			'url'=>'javascript:void(0);','linkOptions'=>array('id'=>'menu_2','class'=>'menu_2'),  
			'itemOptions'=>array('id'=>'menu_2'),
			'items'=>array(
				array(
					'label'=>t('cms','Create Term'), 
					'url'=>array('/term/create'),
					'active'=>Yii::app()->controller->id=='term' && Yii::app()->controller->action->id=='create'
				),
				array(
					'label'=>t('cms','Manage Terms'), 
					'url'=>array('/term/admin'),
					'active'=> ((Yii::app()->controller->id=='term') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index'))) ? true : false)                                                                                           
				),
				array(
					'label'=>t('cms','Create Taxonomy'), 
					'url'=>array('/taxonomy/create'),
					'active'=>Yii::app()->controller->id=='taxonomy' && Yii::app()->controller->action->id=='create'
				),
				array(
					'label'=>t('cms','Mangage Taxonomy'), 
					'url'=>array('/taxonomy/admin'),
					'active'=> ((Yii::app()->controller->id=='taxonomy') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index')))) ? true : false)                                                                                     
				),
				
			),

      //Page Menu 
      	array(
      		'label'=>'<span id="menu_page" class="micon"></span>'.t('cms','Pages'), 
      		'url'=>'javascript:void(0);',
      		'linkOptions'=>array('id'=>'menu_3','class'=>'menu_3'), 
      		'itemOptions'=>array('id'=>'menu_3'),
      		'items'=>array(
      			array(
      				'label'=>t('cms','Create Menu'), 
      				'url'=>array('/menu/create'),
      				'active'=>Yii::app()->controller->id=='menu' && Yii::app()->controller->action->id=='create'
      			),
      			array(
      				'label'=>t('cms','Manage Menus'), 
      				'url'=>array('/menu/admin'),
      				'active'=> ((Yii::app()->controller->id=='menu') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index'))) ? true : false)
      			),
      			array(
      				'label'=>t('cms','Create Queue'), 
      				'url'=>array('/contentlist/create'),
      				'active'=>Yii::app()->controller->id=='contentlist' && Yii::app()->controller->action->id=='create'
      				
      			),
      			array(
      				'label'=>t('cms','Manage Queues'), 
      				'url'=>array('/contentlist/admin'),
      				'active'=> ((Yii::app()->controller->id=='contentlist') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index'))) ? true : false)
      			),
      			array(
      				'label'=>t('cms','Create Block'), 
      				'url'=>array('block/create'),
      				'active'=>Yii::app()->controller->id=='block' && Yii::app()->controller->action->id=='create'
      			),
      			array(
      				'label'=>t('cms','Manage Blocks'), 
      				'url'=>array('/block/admin'),
      				'active'=> ((Yii::app()->controller->id=='block') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index'))) ? true : false)
      			),
      			array(
      				'label'=>t('cms','Create Page'), 
      				'url'=>array('/page/create'),
      				'active'=>Yii::app()->controller->id=='page' && Yii::app()->controller->action->id=='create'
      			),
      			array(
      				'label'=>t('cms','Manage Pages'), 
      				'url'=>array('/page/admin'),
      				'active'=> ((Yii::app()->controller->id=='page') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index')))) ? true : false
      			)
      		)
      ),

      //Resource Menu 
      array(
      		'label'=>'<span id="menu_resource" class="micon"></span>'.t('cms','Resource'), 
      		'url'=>'javascript:void(0);',
      		'linkOptions'=>array('id'=>'menu_4','class'=>'menu_4'), 
      		'itemOptions'=>array('id'=>'menu_4'), 
      		'items'=>array(
      			array(
      				'label'=>t('cms','Create Resource'), 
      				'url'=>array('/resource/create'),
      				'active'=>Yii::app()->controller->id=='resource' && Yii::app()->controller->action->id=='create'      				
      			),
      			array(
      				'label'=>t('cms','Manage Resource'), 
      				'url'=>array('/resource/admin'),
      				'active'=> ((Yii::app()->controller->id=='resource') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index')))) ? true : false
      			)
      		)
      ),

      //Manage Menu 
      array(
      		'label'=>'<span id="menu_manage" class="micon"></span>'.t('cms','Manage'), 
      		'url'=>'javascript:void(0);',
      		'linkOptions'=>array('id'=>'menu_5','class'=>'menu_5'), 
      		'itemOptions'=>array('id'=>'menu_5'), 
      		'items'=>array(
      			array(
      				'label'=>t('cms','Comments'), 
      				'url'=>array('/comment/admin'),
      				'active'=>Yii::app()->controller->id=='comment' ? true : false
      			),
      		)
      ),

      //User Menu 
      array(
      	'label'=>'<span id="menu_user" class="micon"></span>'.t('cms','User'), 
      	'url'=>'javascript:void(0);',
      	'linkOptions'=>array('id'=>'menu_6','class'=>'menu_6'), 
      	'itemOptions'=>array('id'=>'menu_6'), 
      	'items'=>array(
      		array(
      			'label'=>t('cms','Create User'), 
      			'url'=>array('/user/create'),
      			'active'=>Yii::app()->controller->id=='user' && Yii::app()->controller->action->id=='create'
      		),
      		array(
      			'label'=>t('cms','Manage Users'), 
      			'url'=>array('/user/admin'),
      			'active'=> ((Yii::app()->controller->id=='user') && (in_array(Yii::app()->controller->action->id,array('update','view','admin','index')))) ? true : false
      		),
      		array(
      			'label'=>t('cms','Permission'), 
      			'url'=>array('/rights/assignment'),
      			'active'=>in_array(Yii::app()->controller->id,array('assignment','authItem')) ?true:false
      		),
      	),
      	'visible'=>user()->isAdmin ? true : false,   
      ),      

      //Settings Menu 
      array(
      	'label'=>'<span id="menu_setting" class="micon"></span>'.t('cms','Settings'), 
      	'url'=>'javascript:void(0);','linkOptions'=>array('id'=>'menu_7','class'=>'menu_7'), 
      	'itemOptions'=>array('id'=>'menu_7'), 
      	'items'=>array(
      		array(
      			'label'=>t('cms','General'), 
      			'url'=>array('/settings/index/type/general'),
      			'active'=>Yii::app()->controller->id=='settings' && isset($_GET['type']) && $_GET['type']=='general'
      		),
      		array(
      			'label'=>t('cms','System'), 
      			'url'=>array('/settings/index/type/system'),
      			'active'=>Yii::app()->controller->id=='settings' && isset($_GET['type']) && $_GET['type']=='system'
      		),

      	),
      	'visible'=>user()->isAdmin ? true : false,   
      ),

      //Caching Menu 
      array(
      	'label'=>'<span id="menu_caching" class="micon"></span>'.t('cms','Caching'), 
      	'url'=>array('cache/default'),'linkOptions'=>array('id'=>'menu_8','class'=>'menu_8','target'=>'_blank'), 
      	'itemOptions'=>array('id'=>'menu_8'), 
      	'items'=>array(
      	),
      	'visible'=>user()->isAdmin ? true : false,   
      	'active'=>Yii::app()->controller->id=='caching'
      )

    ),
));