cms_core/core/cms/apps/backend/protected/controllers/TaxonomyController.php
<?php
/**
 * Backend Taxonomy Controller.
 * 
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class TaxonomyController extends BeController{
    
       
        public function __construct($id,$module=null)
	{
		 parent::__construct($id,$module);
                 $this->menu=array(
                        array('label'=>t('cms','Manage Taxonomy'), 'url'=>array('admin'),'linkOptions'=>array('class'=>'button')),
                        array('label'=>t('cms','Define Taxonomy'), 'url'=>array('create'),'linkOptions'=>array('class'=>'button')),
                );
		 
	}
                 
        /**
	 * The function that do Create new Taxonomy
	 * 
	 */
	public function actionCreate()
	{                
		$this->render('taxonomy_create');
	}
        
       
        
        /**
	 * The function that do Manage Taxonomy
	 * 
	 */
	public function actionAdmin()
	{                
		$this->render('taxonomy_admin');
	}
        
        /**
	 * The function that view Taxonomy details
	 * 
	 */
	public function actionView()
	{         
              $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
              $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Taxonomy'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Taxonomy'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('taxonomy_view');
	}
        
        /**
	 * The function that update Taxonomy
	 * 
	 */
	public function actionUpdate()
	{                
                $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;                
                $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Taxonomy'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Taxonomy'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('taxonomy_update',array('id'=>$id));
	}
        
        
        /**
	 * The function is to Delete Taxonomy
	 * 
	 */
	public function actionDelete($id)
	{                            
             GxcHelpers::deleteModel('Taxonomy', $id);          
	}
                    
}

cms_core/core/cms/apps/backend/protected/controllers/TermController.php
<?php
/**
 * Backend Term Controller.
 * 
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class TermController extends BeController{
    
       
        public function __construct($id,$module=null)
	{
		 parent::__construct($id,$module);
                 $this->menu=array(
                        array('label'=>t('cms','Manage Terms'), 'url'=>array('admin'),'linkOptions'=>array('class'=>'button')),
                        array('label'=>t('cms','Add Term'), 'url'=>array('create'),'linkOptions'=>array('class'=>'button')),
                );
		 
	}
                 
        /**
	 * The function that do Create new Term
	 * 
	 */
	public function actionCreate()
	{                
                
		$this->render('term_create');
	}
        
        
       
        
        /**
	 * The function that do Manage Term
	 * 
	 */
	public function actionAdmin()
	{                
		$this->render('term_admin');
	}
        
        /**
	 * The function that view Term details
	 * 
	 */
	public function actionView()
	{         
              $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
              $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Term'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Term'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('term_view');
	}
        
        /**
	 * The function that update Term
	 * 
	 */
	public function actionUpdate()
	{                
                $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;                
                $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Term'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Term'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('term_update',array());
	}
        
        
        /**
	 * The function is to Delete Term
	 * 
	 */
	public function actionDelete($id)
	{                              
             Term::ajaxDeleteModel($id);
	}
        
         /**
	 * The function is to Delete Term
	 * 
	 */
	public function actionChangeOrder()
	{                                     
             Term::ajaxChangeOrder();
	}
        
        /**
         * 
         * This function is generate Terms based on Taxonomy Id
         */
        public function actionDynamicParentTerms(){
            $taxonomy_id= (int) ($_POST['Term']['taxonomy_id']);
            Term::getTermFromTaxonomy($taxonomy_id);
        }
                    
}

cms_core/core/cms/apps/backend/protected/views/taxonomy/taxonomy_admin.php
<?php 
$this->pageTitle=t('cms','Manage Taxonomy');
$this->pageHint=t('cms','Here you can manage your Taxonomy'); 
?>
<?php $this->widget('cmswidgets.ModelManageWidget',array('model_name'=>'Taxonomy')); 
?>

cms_core/core/cms/apps/backend/protected/views/taxonomy/taxonomy_create.php
<?php 
$this->pageTitle=t('cms','Add new Taxonomy');
$this->pageHint=t('cms','Here you can add new Taxonomy for your Content Type'); 
?>
<?php $this->widget('cmswidgets.object.TaxonomyCreateWidget',array()); 
?>

cms_core/core/cms/apps/backend/protected/views/taxonomy/taxonomy_update.php
<?php 
$this->pageTitle=t('cms','Update Taxonomy');
$this->pageHint=t('cms','Here you can update information for current Taxonomy'); 
?>
<?php 
$form_create_url=Yii::app()->controller->createUrl('term/create',array('embed'=>'iframe','taxonomy'=>$id));    
$form_update_url=Yii::app()->controller->createUrl('term/update',array('embed'=>'iframe','taxonomy'=>$id));    
$form_change_order_url=Yii::app()->controller->createUrl('term/changeorder',array());    
$form_delete_url=Yii::app()->controller->createUrl('term/delete',array());  
$this->widget('cmswidgets.object.TaxonomyUpdateWidget',array(
    'form_create_term_url'=>$form_create_url,
    'form_update_term_url'=>$form_update_url,
    'form_delete_term_url'=>$form_delete_url,
    'form_change_order_term_url'=>$form_change_order_url,
        )); 
?>

cms_core/core/cms/apps/backend/protected/views/taxonomy/taxonomy_view.php
<?php 
$this->pageTitle=t('cms','Taxonomy details');
$this->widget('cmswidgets.ModelViewWidget',array('model_name'=>'Taxonomy')); 
?>