code/backend/protected/controllers/BlockController.php
<?php
/**
 * Backend Block Controller.
 * 
 * @author Tuan Nguyen <nganhtuan63@gmail.com>
 * @version 1.0
 * @package backend.controllers
 *
 */
class BlockController extends BeController{
    
       
        public function __construct($id,$module=null)
	{
		 parent::__construct($id,$module);
                 $this->menu=array(
                        array('label'=>t('cms','Manage Block'), 'url'=>array('admin'),'linkOptions'=>array('class'=>'button')),
                        array('label'=>t('cms','Add Block'), 'url'=>array('create'),'linkOptions'=>array('class'=>'button')),
                );
		 
	}
                 
        /**
	 * The function that do Create new Block
	 * 
	 */
	public function actionCreate()
	{                
		$this->render('block_create');
	}
        
       
        
        /**
	 * The function that do Manage Block
	 * 
	 */
	public function actionAdmin()
	{                
		$this->render('block_admin');
	}
        
        /**
	 * The function that view Block details
	 * 
	 */
	public function actionView()
	{         
              $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;
              $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Block'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Block'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('block_view');
	}
        
        /**
	 * The function that update Block
	 * 
	 */
	public function actionUpdate()
	{                
                $id=isset($_GET['id']) ? (int) ($_GET['id']) : 0 ;                
                $this->menu=array_merge($this->menu,                       
                        array(
                            array('label'=>t('cms','Update this Block'), 'url'=>array('update','id'=>$id),'linkOptions'=>array('class'=>'button')),
                            array('label'=>t('cms','View this Block'), 'url'=>array('view','id'=>$id),'linkOptions'=>array('class'=>'button'))
                        )
                    );
		$this->render('block_update',array('id'=>$id));
	}
        
        
        /**
	 * The function is to Delete Block
	 * 
	 */
	public function actionDelete($id)
	{                            
             GxcHelpers::deleteModel('Block', $id);          
	}
        
        
    public function actionSuggestBlock()
    {
        $this->render('block_suggest',array());   
    }
    
    
    public function actionSuggestBlocks(){
          Block::suggestBlocks();
    }
        
      
                    
}

code/backend/protected/views/page/page_admin.php
<?php 
$this->pageTitle=t('cms','Manage Pages');
$this->pageHint=t('cms','Here you can manage your Pages'); 
?>
<?php $this->widget('cmswidgets.ModelManageWidget',array('model_name'=>'Page')); 
?>

code/backend/protected/views/page/page_create.php
<?php 
$this->pageTitle=t('cms','Add new Page');
$this->pageHint=t('cms','Here you can add new Page for your Site'); 

?>

<?php 
$add_existed_block_url=Yii::app()->controller->createUrl('block/suggestblock',array('embed'=>'iframe'));    
$add_new_block_url=Yii::app()->controller->createUrl('block/create',array());    
$update_block_url=Yii::app()->controller->createUrl('block/update',array('embed'=>'iframe'));  
$this->widget('cmswidgets.page.PageCreateWidget',array(
    'add_existed_block_url'=>$add_existed_block_url,
    'add_new_block_url'=>$add_new_block_url,
    'update_block_url'=>$update_block_url,
    
)); 
?>

code/backend/protected/views/page/page_update.php
<?php 
$this->pageTitle=t('cms','Update Page');
$this->pageHint=t('cms','Here you can update information for current Page'); 
?>
<?php 
$add_existed_block_url=Yii::app()->controller->createUrl('block/suggestblock',array('embed'=>'iframe'));    
$add_new_block_url=Yii::app()->controller->createUrl('block/create',array());    
$update_block_url=Yii::app()->controller->createUrl('block/update',array('embed'=>'iframe')); 
$this->widget('cmswidgets.page.PageUpdateWidget',array(
    'add_existed_block_url'=>$add_existed_block_url,
    'add_new_block_url'=>$add_new_block_url,
    'update_block_url'=>$update_block_url,    
)); 
?>

code/backend/protected/views/page/page_view.php
<?php 
$this->pageTitle=t('cms','Page details');
$this->widget('cmswidgets.ModelViewWidget',array('model_name'=>'Page')); 
?>